BlockCalc_2/ITUniver.Calc.WebCalc/Controllers/CalcController.cs
using BlockCalc_2;
using ITUniver.Calc.DB.Models;
using ITUniver.Calc.DB.Repositories;
using System;
using System.Linq;
using System.Web.Mvc;
using WebCalc.Models;

namespace WebCalc.Controllers
{
    [Authorize]
    public class CalcController : Controller
    {
        private IHistoryRepository HistoryRepository = new HistoryRepository();

        private IOperationRepository OperationRepository = new OperationRepository();

        // GET: Calc
        public ActionResult Index()
        {
            var calc = new My_Expression();

            var model = new OperationModel();

            model.Operations = calc.GetOpers().Select(
                o => new SelectListItem() {
                    Text = $"{o.Name}",
                    Value = $"{o.Name}"
                });

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(OperationModel model)
        {
            var calc = new My_Expression();

            model.Operations = calc.GetOpers().Select(o => new SelectListItem() { Text = $"{o.Name}", Value = $"{o.Name}" });

            model.Result = calc.Exec(model.Operation, model.Args.ToArray());

            #region Сохранение в HistoryRepository

            var item = new HistoryItem();
            item.Args = string.Join(" ", model.Args);
            item.Operation = 1;//oper;
            item.Result = model.Result;
            item.ExecDate = DateTime.Now;

            HistoryRepository.Save(item);

            #endregion

            return View(model);
        }

        // GET: Calc
        public ActionResult History()
        {
            var history = HistoryRepository.GetAll();
            return View(history);
        }
    }
}

BlockCalc_2/ITUniver.Calc.WebCalc/Controllers/OperationController.cs
using ITUniver.Calc.DB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebCalc.Controllers
{
    [Authorize]
    public class OperationController : Controller
    {
        // GET: Operation
        public ActionResult Index()
        {
            var operations = new List<Operation>()
            {
                new Operation() { Id = 1, ArgsCount = 2, Name = "sum", Owner = "ituniver", CreationDate = DateTime.Now },
                new Operation() { Id = 1, ArgsCount = 2, Name = "sub", Owner = "ituniver", CreationDate = DateTime.Now },
                new Operation() { Id = 1, ArgsCount = 2, Name = "div", Owner = "ituniver", CreationDate = DateTime.Now },
                new Operation() { Id = 1, ArgsCount = 2, Name = "pow", Owner = "ituniver", CreationDate = DateTime.Now },
                new Operation() { Id = 1, ArgsCount = 2, Name = "credit", Owner = "ituniver", CreationDate = DateTime.Now },
            };

            return View(operations);
        }
    }
}

BlockCalc_2/ITUniver.Calc.WebCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Калькулятор</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Вычислитель", "Index", "Calc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("История", "History", "Calc")</li>
                    <li>@Html.ActionLink("Операции", "Index", "Operation")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@User.Identity.Name</li>
                        <li>@Html.ActionLink("Выйти", "Logout", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ITUniver Company</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>